### ISSUE TITLE
Grid for objects placement

### ISSUE THREAD

**Issue by fntneves** [danilowoz/create-vue-content-loader#10]
Hello,

Before anything else, let me congratulate @danilowoz for this amazing tool!

I am finding difficulties on aligning items while building a custom content loader placeholder.
My suggestion is to optionally make a grid available to help  objects placement practical.

Something like this: https://jbaysolutions.github.io/vue-grid-layout/examples/01-basic.html

**Comment by danilowoz** [comment]
Thanks for your thoughts @fntneves, I really appreciate that!
I'm planning a new version from scratch of the creator, so I will consider your suggestion 

Cheers
